#!/usr/bin/env python3
"""Generate HTML API docs for ccai9012 using pdoc.

This script is intentionally small and stable so it can be invoked from:
- CI / tests
- local docs build scripts

Output layout (desired final layout):
- docs/html/api/ccai9012/<module>.html (and related assets generated by pdoc)

Notes
-----
We intentionally *don't* generate Markdown for API docs anymore.
We generate HTML directly via pdoc (or pdoc3):

  pdoc --html --output-dir docs/html/api ccai9012

pdoc typically writes into <output-dir>/<package>/..., so the effective output
becomes docs/html/api/ccai9012/...

After generating HTML, docs/md_to_html.py can still:
- ensure the site-wide CSS is present
- patch the pdoc HTML to use the unified CSS
- inject Starter Kit backlinks
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path


def _which(cmd: str) -> str | None:
    return shutil.which(cmd)


def _run_pdoc_html(*, package: str, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    # Prefer `pdoc` (pdoc v15+). If not available, fallback to `pdoc3`.
    exe = _which("pdoc") or _which("pdoc3")
    if not exe:
        raise FileNotFoundError("Neither 'pdoc' nor 'pdoc3' found on PATH")

    subprocess.run(
        [exe, "--html", "--output-dir", str(out_dir), "--force", package],
        check=True,
        text=True,
    )


def generate_api_html(*, docs_dir: Path | None = None, package: str = "ccai9012", out_dir: Path | None = None) -> Path:
    """Generate HTML API docs and return the output directory used."""

    if docs_dir is None:
        docs_dir = Path(__file__).parent

    if out_dir is None:
        # Final site output location.
        out_dir = docs_dir / "html" / "api"

    _run_pdoc_html(package=package, out_dir=out_dir)
    return out_dir


def main() -> None:
    generate_api_html()


if __name__ == "__main__":
    main()

